# Generated by Django 5.0.1 on 2024-01-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('s_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
